using DfE.GIAP.Core.Downloads.Application.Models;
using DfE.GIAP.Core.Downloads.Application.Models.DownloadOutputs;

namespace DfE.GIAP.Core.Downloads.Application.Aggregators.Handlers.Mappers;

public class NationalPupilToKs2OutputRecordMapper : IMapper<NationalPupil, IEnumerable<KS2Output>>
{
    public IEnumerable<KS2Output> Map(NationalPupil input)
    {
        ArgumentNullException.ThrowIfNull(input);

        if (input.KeyStage2 is null || !input.KeyStage2.Any())
            return Enumerable.Empty<KS2Output>();

        return input.KeyStage2.Select(keyStage2Entry => new KS2Output
        {
            ACADYR = keyStage2Entry?.ACADYR,
            PupilMatchingRef = keyStage2Entry?.PupilMatchingRef,
            CANDNO = keyStage2Entry?.CANDNO,
            CAND_ID = keyStage2Entry?.CAND_ID,
            UPN = keyStage2Entry?.UPN,
            FORENAMES = keyStage2Entry?.FORENAMES,
            SURNAME = keyStage2Entry?.SURNAME,
            DOB = keyStage2Entry?.DOB,
            YEARGRP = keyStage2Entry?.YEARGRP,
            SEX = keyStage2Entry?.SEX,
            LA = keyStage2Entry?.LA,
            LA_9Code = keyStage2Entry?.LA_9Code,
            ESTAB = keyStage2Entry?.ESTAB,
            LAESTAB = keyStage2Entry?.LAESTAB,
            ToE_CODE = keyStage2Entry?.ToE_CODE,
            NFTYPE = keyStage2Entry?.NFTYPE,
            MMSCH = keyStage2Entry?.MMSCH,
            MMSCH2 = keyStage2Entry?.MMSCH2,
            MSCH = keyStage2Entry?.MSCH,
            MSCH2 = keyStage2Entry?.MSCH2,
            URN = keyStage2Entry?.URN,
            URN_AC = keyStage2Entry?.URN_AC,
            OPEN_AC = keyStage2Entry?.OPEN_AC,
            AMDPUPIL = keyStage2Entry?.AMDPUPIL,
            ENDKS = keyStage2Entry?.ENDKS,
            EXAMYEAR_RE = keyStage2Entry?.EXAMYEAR_RE,
            EXAMYEAR_MA = keyStage2Entry?.EXAMYEAR_MA,
            EXAMYEAR_GPS = keyStage2Entry?.EXAMYEAR_GPS,
            SCHRES = keyStage2Entry?.SCHRES,
            LARES = keyStage2Entry?.LARES,
            NATRES = keyStage2Entry?.NATRES,
            NATRESTA = keyStage2Entry?.NATRESTA,
            NATMTDRES = keyStage2Entry?.NATMTDRES,
            NATMTDRESTA = keyStage2Entry?.NATMTDRESTA,
            NPDDEN_LA = keyStage2Entry?.NPDDEN_LA,
            NPDDEN_NAT = keyStage2Entry?.NPDDEN_NAT,
            SCHRESTA = keyStage2Entry?.SCHRESTA,
            LARESTA = keyStage2Entry?.LARESTA,
            READOUTCOME = keyStage2Entry?.READOUTCOME,
            MATOUTCOME = keyStage2Entry?.MATOUTCOME,
            GPSOUTCOME = keyStage2Entry?.GPSOUTCOME,
            READSCORE = keyStage2Entry?.READSCORE,
            READSCORE_noSpeccon = keyStage2Entry?.READSCORE_noSpeccon,
            MATSCORE = keyStage2Entry?.MATSCORE,
            MATSCORE_noSpeccon = keyStage2Entry?.MATSCORE_noSpeccon,
            GPSSCORE = keyStage2Entry?.GPSSCORE,
            GPSSCORE_noSpeccon = keyStage2Entry?.GPSSCORE_noSpeccon,
            READSPECCON = keyStage2Entry?.READSPECCON,
            MATSPECCON = keyStage2Entry?.MATSPECCON,
            GPSSPECCON = keyStage2Entry?.GPSSPECCON,
            WRITTAOUTCOME = keyStage2Entry?.WRITTAOUTCOME,
            SCITAOUTCOME = keyStage2Entry?.SCITAOUTCOME,
            MATTAOUTCOME = keyStage2Entry?.MATTAOUTCOME,
            READTAOUTCOME = keyStage2Entry?.READTAOUTCOME,
            ELIGREAD = keyStage2Entry?.ELIGREAD,
            ELIGMAT = keyStage2Entry?.ELIGMAT,
            ELIGGPS = keyStage2Entry?.ELIGGPS,
            ELIGREADTA = keyStage2Entry?.ELIGREADTA,
            ELIGMATTA = keyStage2Entry?.ELIGMATTA,
            ELIGSCITA = keyStage2Entry?.ELIGSCITA,
            ELIGWRITTA = keyStage2Entry?.ELIGWRITTA,
            ELIGREADLA = keyStage2Entry?.ELIGREADLA,
            ELIGMATLA = keyStage2Entry?.ELIGMATLA,
            ELIGGPSLA = keyStage2Entry?.ELIGGPSLA,
            ELIGWRITTALA = keyStage2Entry?.ELIGWRITTALA,
            ELIGRWMLA = keyStage2Entry?.ELIGRWMLA,
            VALREAD = keyStage2Entry?.VALREAD,
            VALMAT = keyStage2Entry?.VALMAT,
            VALGPS = keyStage2Entry?.VALGPS,
            VALREADTA = keyStage2Entry?.VALREADTA,
            VALMATTA = keyStage2Entry?.VALMATTA,
            VALSCITA = keyStage2Entry?.VALSCITA,
            VALWRITTA = keyStage2Entry?.VALWRITTA,
            READEXP = keyStage2Entry?.READEXP,
            MATEXP = keyStage2Entry?.MATEXP,
            GPSEXP = keyStage2Entry?.GPSEXP,
            READHIGH = keyStage2Entry?.READHIGH,
            MATHIGH = keyStage2Entry?.MATHIGH,
            GPSHIGH = keyStage2Entry?.GPSHIGH,
            READAT = keyStage2Entry?.READAT,
            MATAT = keyStage2Entry?.MATAT,
            GPSAT = keyStage2Entry?.GPSAT,
            READMRK = keyStage2Entry?.READMRK,
            MATMRK = keyStage2Entry?.MATMRK,
            GPSMRK = keyStage2Entry?.GPSMRK,
            GPSPAPER1MRK = keyStage2Entry?.GPSPAPER1MRK,
            GPSPAPER2MRK = keyStage2Entry?.GPSPAPER2MRK,
            MATPAPER2MRK = keyStage2Entry?.MATPAPER2MRK,
            MATPAPER3MRK = keyStage2Entry?.MATPAPER3MRK,
            MATARITHMRK = keyStage2Entry?.MATARITHMRK,
            WRITTAEXP = keyStage2Entry?.WRITTAEXP,
            SCITAEXP = keyStage2Entry?.SCITAEXP,
            WRITTADEPTH = keyStage2Entry?.WRITTADEPTH,
            WRITTAWTS = keyStage2Entry?.WRITTAWTS,
            WRITTABEXP = keyStage2Entry?.WRITTABEXP,
            SCITABEXP = keyStage2Entry?.SCITABEXP,
            WRITTAAD = keyStage2Entry?.WRITTAAD,
            SCITAAD = keyStage2Entry?.SCITAAD,
            ELIGRWM = keyStage2Entry?.ELIGRWM,
            VALRWM = keyStage2Entry?.VALRWM,
            RWMEXP = keyStage2Entry?.RWMEXP,
            RWMHIGH = keyStage2Entry?.RWMHIGH,
            INREADPROG = keyStage2Entry?.INREADPROG,
            INWRITPROG = keyStage2Entry?.INWRITPROG,
            INMATPROG = keyStage2Entry?.INMATPROG,
            KS1AVERAGE_GRP_P = keyStage2Entry?.KS1AVERAGE_GRP_P,
            KS2READSCORE = keyStage2Entry?.KS2READSCORE,
            KS2MATSCORE = keyStage2Entry?.KS2MATSCORE,
            KS2WRITSCORE = keyStage2Entry?.KS2WRITSCORE,
            KS2READPRED_EM = keyStage2Entry?.KS2READPRED_EM,
            KS2WRITPRED_EM = keyStage2Entry?.KS2WRITPRED_EM,
            KS2MATPRED_EM = keyStage2Entry?.KS2MATPRED_EM,
            READPROGSCORE_EM = keyStage2Entry?.READPROGSCORE_EM,
            WRITPROGSCORE_EM = keyStage2Entry?.WRITPROGSCORE_EM,
            MATPROGSCORE_EM = keyStage2Entry?.MATPROGSCORE_EM,
            READPROGSCORE_EM_ADJUSTED = keyStage2Entry?.READPROGSCORE_EM_ADJUSTED,
            WRITPROGSCORE_EM_ADJUSTED = keyStage2Entry?.WRITPROGSCORE_EM_ADJUSTED,
            MATPROGSCORE_EM_ADJUSTED = keyStage2Entry?.MATPROGSCORE_EM_ADJUSTED,
            KS1READPS = keyStage2Entry?.KS1READPS,
            KS1WRITPS = keyStage2Entry?.KS1WRITPS,
            KS1MATPS = keyStage2Entry?.KS1MATPS,
            EALGRP = keyStage2Entry?.EALGRP,
            CLA_PP_1_DAY = keyStage2Entry?.CLA_PP_1_DAY,
            CLA_6_MONTHS = keyStage2Entry?.CLA_6_MONTHS,
            CLA_12_MONTHS = keyStage2Entry?.CLA_12_MONTHS,
            CLA_PP_6_MONTHS = keyStage2Entry?.CLA_PP_6_MONTHS,
            SENTYPE = keyStage2Entry?.SENTYPE,
            KS1GROUP = keyStage2Entry?.KS1GROUP,
            FSM = keyStage2Entry?.FSM,
            FSM6 = keyStage2Entry?.FSM6,
            FSM6_P = keyStage2Entry?.FSM6_P,
            NEWMOBILE = keyStage2Entry?.NEWMOBILE,
            READEXP_noSpeccon = keyStage2Entry?.READEXP_noSpeccon,
            MATEXP_noSpeccon = keyStage2Entry?.MATEXP_noSpeccon,
            GPSEXP_noSpeccon = keyStage2Entry?.GPSEXP_noSpeccon,
            READHIGH_noSpeccon = keyStage2Entry?.READHIGH_noSpeccon,
            MATHIGH_noSpeccon = keyStage2Entry?.MATHIGH_noSpeccon,
            GPSHIGH_noSpeccon = keyStage2Entry?.GPSHIGH_noSpeccon,
            RWMEXP_noSpeccon = keyStage2Entry?.RWMEXP_noSpeccon,
            RWMHIGH_noSpeccon = keyStage2Entry?.RWMHIGH_noSpeccon,
            INREADPROG_noSpeccon = keyStage2Entry?.INREADPROG_noSpeccon,
            INMATPROG_noSpeccon = keyStage2Entry?.INMATPROG_noSpeccon,
            KS2READSCORE_noSpeccon = keyStage2Entry?.KS2READSCORE_noSpeccon,
            KS2MATSCORE_noSpeccon = keyStage2Entry?.KS2MATSCORE_noSpeccon,
            KS2READPRED_EM_noSpeccon = keyStage2Entry?.KS2READPRED_EM_noSpeccon,
            KS2MATPRED_EM_noSpeccon = keyStage2Entry?.KS2MATPRED_EM_noSpeccon,
            READPROGSCORE_EM_noSpeccon = keyStage2Entry?.READPROGSCORE,
            MATPROGSCORE_EM_noSpeccon = keyStage2Entry?.MATPROGSCORE_EM_noSpeccon,
            READPROGSCORE_EM_ADJUSTED_noSpeccon = keyStage2Entry?.READPROGSCORE_EM_ADJUSTED_noSpeccon,
            MATPROGSCORE_EM_ADJUSTED_noSpeccon = keyStage2Entry?.MATPROGSCORE_EM_ADJUSTED_noSpeccon,
            VERSION = keyStage2Entry?.VERSION
        });
    }
}
