namespace DfE.GIAP.Core.Downloads.Application.Models.DownloadOutputs;

public class KS4OutputRecord
{
    public string? KS4_ACADYR { get; set; }
    public string? KS4_PUPILMATCHINGREF { get; set; }
    public string? KS4_UPN { get; set; }
    public string? KS4_SURNAME { get; set; }
    public string? KS4_FORENAMES { get; set; }
    public string? KS4_DOB { get; set; }
    public string? KS4_YEARGRP { get; set; }
    public string? KS4_ACTYRGRP { get; set; }
    public string? KS4_SEX { get; set; }
    public string? KS4_LA { get; set; }
    public string? KS4_LA_9CODE { get; set; }
    public string? KS4_ESTAB { get; set; }
    public string? KS4_LAESTAB { get; set; }
    public string? KS4_PDFECN { get; set; }
    public string? KS4_URN { get; set; }
    public string? KS4_URN_AC { get; set; }
    public string? KS4_OPEN_AC { get; set; }
    public string? KS4_TOE_CODE { get; set; }
    public string? KS4_NFTYPE { get; set; }
    public string? KS4_NEW_TYPE { get; set; }
    public string? KS4_NEWER_TYPE { get; set; }
    public string? KS4_MMSCH { get; set; }
    public string? KS4_MMSCH2 { get; set; }
    public string? KS4_MSCH { get; set; }
    public string? KS4_MSCH2 { get; set; }
    public string? KS4_NCN { get; set; }
    public string? KS4_ENTRIES { get; set; }
    public string? KS4_AMDFLAG { get; set; }
    public string? KS4_ENDKS { get; set; }
    public string? KS4_NORFLAGE { get; set; }
    public string? KS4_SCHRES { get; set; }
    public string? KS4_LARES { get; set; }
    public string? KS4_NATRES { get; set; }
    public string? KS4_NATMTDRES { get; set; }
    public string? KS4_SCHNOR { get; set; }
    public string? KS4_LANOR { get; set; }
    public string? KS4_NATNOR { get; set; }
    public string? KS4_NPDDEN_NAT { get; set; }
    public string? KS4_NPDNUM_NAT { get; set; }
    public string? KS4_NPDDEN_LA { get; set; }
    public string? KS4_NPDNUM_LA { get; set; }
    public string? KS4_ALLSCI_PTQ_EE { get; set; }
    public string? KS4_ENT1GMFL_91 { get; set; }
    public string? KS4_ENT1EMFL_PTQ_EE { get; set; }
    public string? KS4_ENTRY_G_PTQ_EE { get; set; }
    public string? KS4_ENTRY_E_3NG_PTQ_EE { get; set; }
    public string? KS4_PTSPE_PTQ_EE { get; set; }
    public string? KS4_GPTSPE_PTQ_EE { get; set; }
    public string? KS4_ENTRY_1_3NG_PTQ_EE { get; set; }
    public string? KS4_ENTRY_5_3NG_PTQ_EE { get; set; }
    public string? KS4_PASS_94 { get; set; }
    public string? KS4_PASS_1_94 { get; set; }
    public string? KS4_PASS_LEV2_PTQ_EE { get; set; }
    public string? KS4_PASS_LEV2EM_PTQ_EE { get; set; }
    public string? KS4_PASS_LEV1_PTQ_EE { get; set; }
    public string? KS4_PASS_LEV1EM_PTQ_EE { get; set; }
    public string? KS4_BTEC_PTQ_EE { get; set; }
    public string? KS4_PTSTNEWE_PTQ_EE { get; set; }
    public string? KS4_PTSCNEWE_PTQ_EE { get; set; }
    public string? KS4_AVPTSENT_PTQ_EE { get; set; }
    public string? KS4_LEVEL2_PTQ_EE { get; set; }
    public string? KS4_GLEVEL2_PTQ_EE { get; set; }
    public string? KS4_GLEVEL2EM_PTQ_EE { get; set; }
    public string? KS4_LEVEL1_PTQ_EE { get; set; }
    public string? KS4_ANYLEV1_PTQ_EE { get; set; }
    public string? KS4_ANYPASS_PTQ_EE { get; set; }
    public string? KS4_VOCQUAL_PTQ_EE { get; set; }
    public string? KS4_HGMATH_91 { get; set; }
    public string? KS4_KS4SCI_91 { get; set; }
    public string? KS4_LEVEL2_EM_94 { get; set; }
    public string? KS4_LEVEL1_EM_PTQ_EE { get; set; }
    public string? KS4_LEV2EM_94 { get; set; }
    public string? KS4_LEV2EM_95 { get; set; }
    public string? KS4_LEV1EM_PTQ_EE { get; set; }
    public string? KS4_LEV2SCIA_94 { get; set; }
    public string? KS4_LEV2SCIA_95 { get; set; }
    public string? KS4_LEV2SCIC_94 { get; set; }
    public string? KS4_LEV2SCIC_95 { get; set; }
    public string? KS4_LEV2SCID_94 { get; set; }
    public string? KS4_LEV2SCID_95 { get; set; }
    public string? KS4_LEV2SCI2_94 { get; set; }
    public string? KS4_LEV2SCI2_95 { get; set; }
    public string? KS4_LEVEL2MFL_94 { get; set; }
    public string? KS4_LEVEL2MFL_95 { get; set; }
    public string? KS4_LEVEL1MFL_PTQ_EE { get; set; }
    public string? KS4_ANYPMFL_PTQ_EE { get; set; }
    public string? KS4_GCSE_ENGATT_PTQ_EE { get; set; }
    public string? KS4_GCSE_ENG_91 { get; set; }
    public string? KS4_GCSE_ENG_94 { get; set; }
    public string? KS4_GCSE_ENG_95 { get; set; }
    public string? KS4_GCSE_MATHATT_PTQ_EE { get; set; }
    public string? KS4_GCSE_MATH_91 { get; set; }
    public string? KS4_GCSE_MATH_94 { get; set; }
    public string? KS4_GCSE_MATH_95 { get; set; }
    public string? KS4_GCSE_SCIATT_PTQ_EE { get; set; }
    public string? KS4_GCSE_SCI_91 { get; set; }
    public string? KS4_GCSE_SCI_94 { get; set; }
    public string? KS4_EBACENG_94 { get; set; }
    public string? KS4_EBACENG_95 { get; set; }
    public string? KS4_EBALLSCI_PTQ_EE { get; set; }
    public string? KS4_PASS2SCIA_94 { get; set; }
    public string? KS4_PASS2SCIA_95 { get; set; }
    public string? KS4_PASS2SCIB_94 { get; set; }
    public string? KS4_PASS2SCIB_95 { get; set; }
    public string? KS4_PASSCOMBSCI_94 { get; set; }
    public string? KS4_PASSCOMBSCI_95 { get; set; }
    public string? KS4_PASSCOMBSCI_91 { get; set; }
    public string? KS4_EBAC2SCI_94 { get; set; }
    public string? KS4_EBAC2SCI_95 { get; set; }
    public string? KS4_EBACMAT_94 { get; set; }
    public string? KS4_EBACMAT_95 { get; set; }
    public string? KS4_EBACHUM_94 { get; set; }
    public string? KS4_EBACHUM_95 { get; set; }
    public string? KS4_EBACLAN_94 { get; set; }
    public string? KS4_EBACLAN_95 { get; set; }
    public string? KS4_EBACC_94 { get; set; }
    public string? KS4_EBACC_95 { get; set; }
    public string? KS4_EBACCAPS_PUPIL { get; set; }
    public string? KS4_L2BASICS_94 { get; set; }
    public string? KS4_L2BASICS_95 { get; set; }
    public string? KS4_EBACENG_E_PTQ_EE { get; set; }
    public string? KS4_EBACMAT_E_PTQ_EE { get; set; }
    public string? KS4_EBAC2SCI_E_PTQ_EE { get; set; }
    public string? KS4_EBACHUM_E_PTQ_EE { get; set; }
    public string? KS4_EBACLAN_E_PTQ_EE { get; set; }
    public string? KS4_EBACC_E_PTQ_EE { get; set; }
    public string? KS4_EBACENG91 { get; set; }
    public string? KS4_PASS2SCIA_91 { get; set; }
    public string? KS4_PASS2SCIB_91 { get; set; }
    public string? KS4_EBAC2SCI_91 { get; set; }
    public string? KS4_EBACMAT91 { get; set; }
    public string? KS4_EBACHUM_91 { get; set; }
    public string? KS4_EBACLAN_91 { get; set; }
    public string? KS4_EBACC91 { get; set; }
    public string? KS4_INSCIVAMOD_PTQ_EE { get; set; }
    public string? KS4_INHUMVAMOD_PTQ_EE { get; set; }
    public string? KS4_INLANVAMOD_PTQ_EE { get; set; }
    public string? KS4_INSCIVACALC_PTQ_EE { get; set; }
    public string? KS4_INHUMVACALC_PTQ_EE { get; set; }
    public string? KS4_INLANVACALC_PTQ_EE { get; set; }
    public string? KS4_SCIVAPRED_PTQ_EE { get; set; }
    public string? KS4_SCIVASCR_PTQ_EE { get; set; }
    public string? KS4_HUMVAPRED_PTQ_EE { get; set; }
    public string? KS4_HUMVASCR_PTQ_EE { get; set; }
    public string? KS4_LANVAPRED_PTQ_EE { get; set; }
    public string? KS4_LANVASCR_PTQ_EE { get; set; }
    public string? KS4_GPTSTNEWE_PTQ_EE { get; set; }
    public string? KS4_GPTSCNEWE_PTQ_EE { get; set; }
    public string? KS4_EBPTSENG_PTQ_EE { get; set; }
    public string? KS4_EBPTSMAT_PTQ_EE { get; set; }
    public string? KS4_EBPTSSCI_PTQ_EE { get; set; }
    public string? KS4_EBPTSHUM_PTQ_EE { get; set; }
    public string? KS4_EBPTSLAN_PTQ_EE { get; set; }
    public string? KS4_PRIORBAND_PTQ_EE { get; set; }
    public string? KS4_EALGRP_PTQ_EE { get; set; }
    public string? KS4_ENGPAIR_PTQ_EE { get; set; }
    public string? KS4_ENGPAIRLEV1_PTQ_EE { get; set; }
    public string? KS4_ENGPAIRLEV2_94 { get; set; }
    public string? KS4_ENGPAIRLEV2_95 { get; set; }
    public string? KS4_APELIT_91 { get; set; }
    public string? KS4_APFOOD_91 { get; set; }
    public string? KS4_APART_91 { get; set; }
    public string? KS4_APHIS_91 { get; set; }
    public string? KS4_APGEO_91 { get; set; }
    public string? KS4_APFRE_91 { get; set; }
    public string? KS4_APGER_91 { get; set; }
    public string? KS4_APBUS_91 { get; set; }
    public string? KS4_APRS_91 { get; set; }
    public string? KS4_APPE_91 { get; set; }
    public string? KS4_APPHY_91 { get; set; }
    public string? KS4_APCHE_91 { get; set; }
    public string? KS4_APBIO_91 { get; set; }
    public string? KS4_APDRA_91 { get; set; }
    public string? KS4_APSPAN_91 { get; set; }
    public string? KS4_APMUS_91 { get; set; }
    public string? KS4_APMAT_91 { get; set; }
    public string? KS4_APENG_91 { get; set; }
    public string? KS4_APSTAT_91 { get; set; }
    public string? KS4_APMFT_91 { get; set; }
    public string? KS4_APITA_91 { get; set; }
    public string? KS4_APMGRK_91 { get; set; }
    public string? KS4_APPOR_91 { get; set; }
    public string? KS4_APARA_91 { get; set; }
    public string? KS4_APBEN_91 { get; set; }
    public string? KS4_APCHI_91 { get; set; }
    public string? KS4_APGUJ_91 { get; set; }
    public string? KS4_APJAP_91 { get; set; }
    public string? KS4_APMHEB_91 { get; set; }
    public string? KS4_APPAN_91 { get; set; }
    public string? KS4_APPOL_91 { get; set; }
    public string? KS4_APRUS_91 { get; set; }
    public string? KS4_APTUR_91 { get; set; }
    public string? KS4_APURD_91 { get; set; }
    public string? KS4_APPER_91 { get; set; }
    public string? KS4_APCGRK_91 { get; set; }
    public string? KS4_APLAT_91 { get; set; }
    public string? KS4_APBHEB_91 { get; set; }
    public string? KS4_APCOMBSCI_91 { get; set; }
    public string? KS4_HPGENG_PTQ_EE { get; set; }
    public string? KS4_HPGMATH_PTQ_EE { get; set; }
    public string? KS4_FSM { get; set; }
    public string? KS4_FSM6 { get; set; }
    public string? KS4_FSM6_P { get; set; }
    public string? KS4_SENK { get; set; }
    public string? KS4_SENE { get; set; }
    public string? KS4_FEMALE { get; set; }
    public string? KS4_FLANG { get; set; }
    public string? KS4_TRIPLESCI_E { get; set; }
    public string? KS4_MULTILAN_E { get; set; }
    public string? KS4_NEWMOBILE { get; set; }
    public string? KS4_ENGRESID { get; set; }
    public string? KS4_ENGRESID_G { get; set; }
    public string? KS4_EBAC4 { get; set; }
    public string? KS4_EBAC5 { get; set; }
    public string? KS4_EBAC6 { get; set; }
    public string? KS4_EBAC4_G { get; set; }
    public string? KS4_EBAC5_G { get; set; }
    public string? KS4_EBAC6_G { get; set; }
    public string? KS4_OTH1 { get; set; }
    public string? KS4_OTH2 { get; set; }
    public string? KS4_OTH3 { get; set; }
    public string? KS4_OTH1_G { get; set; }
    public string? KS4_OTH2_G { get; set; }
    public string? KS4_OTH3_G { get; set; }
    public string? KS4_SLOT1ENG { get; set; }
    public string? KS4_SLOT2MAT { get; set; }
    public string? KS4_SLOT3EBAC { get; set; }
    public string? KS4_SLOT4EBAC { get; set; }
    public string? KS4_SLOT5EBAC { get; set; }
    public string? KS4_SLOT6OPEN { get; set; }
    public string? KS4_SLOT7OPEN { get; set; }
    public string? KS4_SLOT8OPEN { get; set; }
    public string? KS4_SLOT6OPEN_G { get; set; }
    public string? KS4_SLOT7OPEN_G { get; set; }
    public string? KS4_SLOT8OPEN_G { get; set; }
    public string? KS4_ATT8 { get; set; }
    public string? KS4_EBACFILL { get; set; }
    public string? KS4_OPENFILL { get; set; }
    public string? KS4_EBACSCR { get; set; }
    public string? KS4_OPENSCR { get; set; }
    public string? KS4_ATT8_PRED { get; set; }
    public string? KS4_INP8MOD { get; set; }
    public string? KS4_INP8CALC { get; set; }
    public string? KS4_P8SCORE { get; set; }
    public string? KS4_P8SCORE_ORIG { get; set; }
    public string? KS4_P8ADJ { get; set; }
    public string? KS4_AVGP8_GRP { get; set; }
    public string? KS4_SIGMAP8_GRP { get; set; }
    public string? KS4_P8THRESH { get; set; }
    public string? KS4_ENG_PRED { get; set; }
    public string? KS4_P8ENG { get; set; }
    public string? KS4_MAT_PRED { get; set; }
    public string? KS4_P8MAT { get; set; }
    public string? KS4_EBAC_PRED { get; set; }
    public string? KS4_P8EBAC { get; set; }
    public string? KS4_OPEN_PRED { get; set; }
    public string? KS4_P8OPEN { get; set; }
    public string? KS4_OPENGSCR { get; set; }
    public string? KS4_OPENNGSCR { get; set; }
    public string? KS4_GCSE_9 { get; set; }
    public string? KS4_GCSE_8 { get; set; }
    public string? KS4_GCSE_7 { get; set; }
    public string? KS4_GCSE_6 { get; set; }
    public string? KS4_GCSE_5 { get; set; }
    public string? KS4_GCSE_4 { get; set; }
    public string? KS4_GCSE_3 { get; set; }
    public string? KS4_GCSE_2 { get; set; }
    public string? KS4_GCSE_1 { get; set; }
    public string? KS4_GCSE_95 { get; set; }
    public string? KS4_GCSE_94 { get; set; }
    public string? KS4_GCSE_91 { get; set; }
    public string? KS4_PASS_91 { get; set; }
    public string? KS4_FIVE94 { get; set; }
    public string? KS4_FIVE91 { get; set; }
    public string? KS4_PASS_1_91 { get; set; }
    public string? KS4_KS2READSCORETA { get; set; }
    public string? KS4_KS2MATSCORETA { get; set; }
    public string? KS4_KS2READSCORE { get; set; }
    public string? KS4_KS2MATSCORE { get; set; }
    public string? KS4_ENTERED_HISTORY { get; set; }
    public string? KS4_ENTERED_GEOGRAPHY { get; set; }
    public string? KS4_ENTERED_ART { get; set; }
    public string? KS4_EBACCSUBJENT_0 { get; set; }
    public string? KS4_EBACCSUBJENT_1 { get; set; }
    public string? KS4_EBACCSUBJENT_2 { get; set; }
    public string? KS4_EBACCSUBJENT_3 { get; set; }
    public string? KS4_EBACCSUBJENT_4 { get; set; }
    public string? KS4_ENTBASICS { get; set; }
    public string? KS4_ENTERED_HIST_GEOG { get; set; }
    public string? KS4_KS2EMSS { get; set; }
    public string? KS4_KS2EMSS_GRP { get; set; }
    public string? KS4_VERSION { get; set; }
}
