namespace DfE.GIAP.Core.Downloads.Application.Models;

public class KeyStage1Entry
{
    public string? ACADYR { get; set; }
    public string? PUPILMATCHINGREF { get; set; }
    public string? KS1_ID { get; set; }
    public string? UPN { get; set; }
    public string? SURNAME { get; set; }
    public string? FORENAMES { get; set; }
    public string? DOB { get; set; }
    public string? GENDER { get; set; }
    public string? SEX { get; set; }
    public string? LA { get; set; }
    public string? LA_9Code { get; set; }
    public string? ESTAB { get; set; }
    public string? LAESTAB { get; set; }
    public string? URN { get; set; }
    public string? ToE_CODE { get; set; }
    public string? MMSCH { get; set; }
    public string? MMSCH2 { get; set; }
    public string? MSCH { get; set; }
    public string? MSCH2 { get; set; }
    public string? MOB1 { get; set; }
    public string? MOB2 { get; set; }
    public string? DISC_READ { get; set; }
    public string? DISC_WRIT { get; set; }
    public string? DISC_MAT { get; set; }
    public string? DISC_SCI { get; set; }
    public string? DISC_PSENG { get; set; }
    public string? DISC_PSREAD { get; set; }
    public string? DISC_PSWRITE { get; set; }
    public string? DISC_PSSPEAK { get; set; }
    public string? DISC_PSLISTEN { get; set; }
    public string? DISC_PSMATHS { get; set; }
    public string? DISC_PSNUM { get; set; }
    public string? DISC_PSUSING { get; set; }
    public string? DISC_PSSHAPE { get; set; }
    public string? DISC_PSSCIENCE { get; set; }
    public string? READ_OUTCOME { get; set; }
    public string? WRIT_OUTCOME { get; set; }
    public string? MATH_OUTCOME { get; set; }
    public string? SCI_OUTCOME { get; set; }
    public string? PSENG { get; set; }
    public string? PSREAD { get; set; }
    public string? PSWRITE { get; set; }
    public string? PSSPEAK { get; set; }
    public string? PSLISTEN { get; set; }
    public string? PSMATHS { get; set; }
    public string? PSNUM { get; set; }
    public string? PSUSING { get; set; }
    public string? PSSHAPE { get; set; }
    public string? PSSCIENCE { get; set; }
    public string? NPDPUB { get; set; }
    public string? NFTYPE { get; set; }
    public string? SPEAKANDLISTEN { get; set; }
    public string? APS { get; set; }
    public string? READING { get; set; }
    public string? WRITING { get; set; }
    public string? READWRIT { get; set; }
    public string? MATHS { get; set; }
    public string? SCIEXPINVEST { get; set; }
    public string? SCILIFPROT { get; set; }
    public string? SCIMATPROP { get; set; }
    public string? SCIPHYSPROC { get; set; }
    public string? SCIENCE { get; set; }
    public string? VERSION { get; set; }
}
