namespace DfE.GIAP.Core.Downloads.Application.Models;

public class KeyStage2Entry
{
    public string? ACADYR { get; set; }
    public string? PupilMatchingRef { get; set; }
    public string? CANDNO { get; set; }
    public string? CAND_ID { get; set; }
    public string? UPN { get; set; }
    public string? SURNAME { get; set; }
    public string? FORENAMES { get; set; }
    public string? DOB { get; set; }
    public string? YEARGRP { get; set; }
    public string? GENDER { get; set; }
    public string? SEX { get; set; }
    public string? LA { get; set; }
    public string? LA_9Code { get; set; }
    public string? ESTAB { get; set; }
    public string? LAESTAB { get; set; }
    public string? ToE_CODE { get; set; }
    public string? NFTYPE { get; set; }
    public string? MMSCH { get; set; }
    public string? MMSCH2 { get; set; }
    public string? MSCH { get; set; }
    public string? MSCH2 { get; set; }
    public string? URN { get; set; }
    public string? URN_AC { get; set; }
    public string? OPEN_AC { get; set; }
    public string? AMDPUPIL { get; set; }
    public string? ENDKS { get; set; }
    public string? EXAMYEAR_RE { get; set; }
    public string? EXAMYEAR_GPS { get; set; }
    public string? EXAMYEAR_MA { get; set; }
    public string? SCHRES { get; set; }
    public string? LARES { get; set; }
    public string? NATRES { get; set; }
    public string? NATMTDRES { get; set; }
    public string? NPDDEN_LA { get; set; }
    public string? NPDDEN_NAT { get; set; }
    public string? SCHRESTA { get; set; }
    public string? LARESTA { get; set; }
    public string? NATRESTA { get; set; }
    public string? NATMTDRESTA { get; set; }
    public string? EXAMYEAR_EN { get; set; }
    public string? READLEVTA { get; set; }
    public string? WRITLEVTA { get; set; }
    public string? ENGTIER { get; set; }
    public string? ENGWRITMRK { get; set; }
    public string? READLEV { get; set; }
    public string? ENGTOTMRK { get; set; }
    public string? ENGWRITLEV { get; set; }
    public string? ENGLEVTA { get; set; }
    public string? ENGLEV { get; set; }
    public string? MATTIER { get; set; }
    public string? MATTESTAMRK { get; set; }
    public string? MATTESTBMRK { get; set; }
    public string? MATARTHMRK { get; set; }
    public string? MATTOTMRK { get; set; }
    public string? MATLEV { get; set; }
    public string? MATLEVTA { get; set; }
    public string? SCILEVTA { get; set; }
    public string? GPSLEV { get; set; }
    public string? GPS_T2MARK { get; set; }
    public string? GPS_T3MARK { get; set; }
    public string? GPS_TESTMARK { get; set; }
    public string? PSENG { get; set; }
    public string? PSREAD { get; set; }
    public string? PSWRITE { get; set; }
    public string? PSSPEAK { get; set; }
    public string? PSLISTEN { get; set; }
    public string? PSMATHS { get; set; }
    public string? PSNUM { get; set; }
    public string? PSUSING { get; set; }
    public string? PSSHAPE { get; set; }
    public string? PSSCIENCE { get; set; }
    public string? KS2APSFG { get; set; }
    public string? READOUTCOME { get; set; }
    public string? MATOUTCOME { get; set; }
    public string? GPSOUTCOME { get; set; }
    public string? READSCORE { get; set; }
    public string? READSCORE_noSpeccon { get; set; }
    public string? MATSCORE { get; set; }
    public string? MATSCORE_noSpeccon { get; set; }
    public string? GPSSCORE { get; set; }
    public string? GPSSCORE_noSpeccon { get; set; }
    public string? READSPECCON { get; set; }
    public string? MATSPECCON { get; set; }
    public string? GPSSPECCON { get; set; }
    public string? WRITTAOUTCOME { get; set; }
    public string? SCITAOUTCOME { get; set; }
    public string? MATTAOUTCOME { get; set; }
    public string? READTAOUTCOME { get; set; }
    public string? ELIGREAD { get; set; }
    public string? ELIGREADTA { get; set; }
    public string? ELIGWRITTA { get; set; }
    public string? ELIGMAT { get; set; }
    public string? ELIGMATTA { get; set; }
    public string? ELIGREADLA { get; set; }
    public string? ELIGGPSLA { get; set; }
    public string? ELIGWRITTALA { get; set; }
    public string? ELIGMATLA { get; set; }
    public string? ELIGRWMLA { get; set; }
    public string? ELIGSCITA { get; set; }
    public string? ELIGGPS { get; set; }
    public string? VALREAD { get; set; }
    public string? VALREADTA { get; set; }
    public string? VALWRITTA { get; set; }
    public string? VALMAT { get; set; }
    public string? VALMATTA { get; set; }
    public string? VALSCITA { get; set; }
    public string? VALGPS { get; set; }
    public string? READEXP { get; set; }
    public string? MATEXP { get; set; }
    public string? GPSEXP { get; set; }
    public string? READHIGH { get; set; }
    public string? MATHIGH { get; set; }
    public string? GPSHIGH { get; set; }
    public string? READAT { get; set; }
    public string? MATAT { get; set; }
    public string? GPSAT { get; set; }
    public string? READMRK { get; set; }
    public string? GPSPAPER1MRK { get; set; }
    public string? GPSPAPER2MRK { get; set; }
    public string? GPSMRK { get; set; }
    public string? MATPAPER2MRK { get; set; }
    public string? MATPAPER3MRK { get; set; }
    public string? MATARITHMRK { get; set; }
    public string? MATMRK { get; set; }
    public string? WRITTAEXP { get; set; }
    public string? SCITAEXP { get; set; }
    public string? MATTAEXP { get; set; }
    public string? READTAEXP { get; set; }
    public string? WRITTADEPTH { get; set; }
    public string? WRITTAWTS { get; set; }
    public string? WRITTABEXP { get; set; }
    public string? SCITABEXP { get; set; }
    public string? MATTABEXP { get; set; }
    public string? READTABEXP { get; set; }
    public string? WRITTAAD { get; set; }
    public string? SCITAAD { get; set; }
    public string? MATTAAD { get; set; }
    public string? READTAAD { get; set; }
    public string? ELIGRWM { get; set; }
    public string? VALRWM { get; set; }
    public string? RWMEXP { get; set; }
    public string? RWMHIGH { get; set; }
    public string? KS1AVERAGE { get; set; }
    public string? INREADPROG { get; set; }
    public string? INWRITPROG { get; set; }
    public string? INMATPROG { get; set; }
    public string? KS1AVERAGE_GRP { get; set; }
    public string? KS1AVERAGE_GRP_P { get; set; }
    public string? KS2READSCORE { get; set; }
    public string? KS2WRITSCORE { get; set; }
    public string? KS2MATSCORE { get; set; }
    public string? KS2READPRED { get; set; }
    public string? KS2WRITPRED { get; set; }
    public string? KS2MATPRED { get; set; }
    public string? KS2READPRED_P { get; set; }
    public string? KS2WRITPRED_P { get; set; }
    public string? KS2MATPRED_P { get; set; }
    public string? READPROGSCORE { get; set; }
    public string? WRITPROGSCORE { get; set; }
    public string? MATPROGSCORE { get; set; }
    public string? READPROGSCORE_P { get; set; }
    public string? WRITPROGSCORE_P { get; set; }
    public string? MATPROGSCORE_P { get; set; }
    public string? READPROGSCORE_P_ADJUSTED { get; set; }
    public string? WRITPROGSCORE_P_ADJUSTED { get; set; }
    public string? MATPROGSCORE_P_ADJUSTED { get; set; }
    public string? KS1READPS { get; set; }
    public string? KS1WRITPS { get; set; }
    public string? KS1MATPS { get; set; }
    public string? EALGRP { get; set; }
    public string? CLA_PP_1_DAY { get; set; }
    public string? CLA_6_MONTHS { get; set; }
    public string? CLA_12_MONTHS { get; set; }
    public string? CLA_PP_6_MONTHS { get; set; }
    public string? SENTYPE { get; set; }
    public string? KS1GROUP { get; set; }
    public string? FSM { get; set; }
    public string? FSM6 { get; set; }
    public string? FSM6_P { get; set; }
    public string? NEWMOBILE { get; set; }
    public string? KS2READPRED_EM { get; set; }
    public string? KS2WRITPRED_EM { get; set; }
    public string? KS2MATPRED_EM { get; set; }
    public string? READPROGSCORE_EM { get; set; }
    public string? WRITPROGSCORE_EM { get; set; }
    public string? MATPROGSCORE_EM { get; set; }
    public string? READPROGSCORE_EM_ADJUSTED { get; set; }
    public string? WRITPROGSCORE_EM_ADJUSTED { get; set; }
    public string? MATPROGSCORE_EM_ADJUSTED { get; set; }
    public string? READEXP_noSpeccon { get; set; }
    public string? MATEXP_noSpeccon { get; set; }
    public string? GPSEXP_noSpeccon { get; set; }
    public string? READHIGH_noSpeccon { get; set; }
    public string? MATHIGH_noSpeccon { get; set; }
    public string? GPSHIGH_noSpeccon { get; set; }
    public string? RWMEXP_noSpeccon { get; set; }
    public string? RWMHIGH_noSpeccon { get; set; }
    public string? INREADPROG_noSpeccon { get; set; }
    public string? INMATPROG_noSpeccon { get; set; }
    public string? KS2READSCORE_noSpeccon { get; set; }
    public string? KS2MATSCORE_noSpeccon { get; set; }
    public string? KS2READPRED_EM_noSpeccon { get; set; }
    public string? KS2MATPRED_EM_noSpeccon { get; set; }
    public string? READPROGSCORE_EM_noSpeccon { get; set; }
    public string? MATPROGSCORE_EM_noSpeccon { get; set; }
    public string? READPROGSCORE_EM_ADJUSTED_noSpeccon { get; set; }
    public string? MATPROGSCORE_EM_ADJUSTED_noSpeccon { get; set; }
    public string? VERSION { get; set; }
}
