namespace DfE.GIAP.Core.Downloads.Application.Models.Entries;

public class KeyStage4Entry
{
    public string? ACADYR { get; set; }
    public string? PUPILMATCHINGREF { get; set; }
    public string? UPN { get; set; }
    public string? SURNAME { get; set; }
    public string? FORENAMES { get; set; }
    public DateTime? DOB { get; set; }
    public string? YEARGRP { get; set; }
    public string? ACTYRGRP { get; set; }
    public string? SEX { get; set; }
    public string? IDACI { get; set; }
    public string? LA { get; set; }
    public string? LA_9CODE { get; set; }
    public string? ESTAB { get; set; }
    public string? LAESTAB { get; set; }
    public string? PDFECN { get; set; }
    public string? URN { get; set; }
    public string? URN_AC { get; set; }
    public string? OPEN_AC { get; set; }
    public string? TOE_CODE { get; set; }
    public string? NFTYPE { get; set; }
    public string? NEW_TYPE { get; set; }
    public string? NEWER_TYPE { get; set; }
    public string? MMSCH { get; set; }
    public string? MMSCH2 { get; set; }
    public string? MSCH { get; set; }
    public string? MSCH2 { get; set; }
    public string? NCN { get; set; }
    public string? ENTRIES { get; set; }
    public string? AMDFLAG { get; set; }
    public string? ENDKS { get; set; }
    public string? EARLYT_E { get; set; }
    public string? NORFLAGE { get; set; }
    public string? SCHRES { get; set; }
    public string? LARES { get; set; }
    public string? NATRES { get; set; }
    public string? NATMTDRES { get; set; }
    public string? SCHNOR { get; set; }
    public string? LANOR { get; set; }
    public string? NATNOR { get; set; }
    public string? NPDDEN_NAT { get; set; }
    public string? NPDNUM_NAT { get; set; }
    public string? NPDDEN_LA { get; set; }
    public string? NPDNUM_LA { get; set; }
    public string? ALLSCI_PTQ_EE { get; set; }
    public string? ENT1GMFL_91 { get; set; }
    public string? ENT1EMFL_PTQ_EE { get; set; }
    public string? ENTRY_G_PTQ_EE { get; set; }
    public string? ENTRY_E_3NG_PTQ_EE { get; set; }
    public string? PTSPE_PTQ_EE { get; set; }
    public string? GPTSPE_PTQ_EE { get; set; }
    public string? ENTRY_1_3NG_PTQ_EE { get; set; }
    public string? ENTRY_5_3NG_PTQ_EE { get; set; }
    public string? EXAMCAT_PTQ_EE { get; set; }
    public string? PASS_94 { get; set; }
    public string? PASS_1_94 { get; set; }
    public string? PASS_LEV2_PTQ_EE { get; set; }
    public string? PASS_LEV2EM_PTQ_EE { get; set; }
    public string? PASS_LEV1_PTQ_EE { get; set; }
    public string? PASS_LEV1EM_PTQ_EE { get; set; }
    public string? BTEC_PTQ_EE { get; set; }
    public string? PTSTNEWE_PTQ_EE { get; set; }
    public string? PTSCNEWE_PTQ_EE { get; set; }
    public string? AVPTSENT_PTQ_EE { get; set; }
    public string? LEVEL2_PTQ_EE { get; set; }
    public string? GLEVEL2_PTQ_EE { get; set; }
    public string? GLEVEL2EM_PTQ_EE { get; set; }
    public string? LEVEL1_PTQ_EE { get; set; }
    public string? ANYLEV1_PTQ_EE { get; set; }
    public string? ANYPASS_PTQ_EE { get; set; }
    public string? VOCQUAL_PTQ_EE { get; set; }
    public string? HGMATH_91 { get; set; }
    public string? KS4SCI_91 { get; set; }
    public string? LEVEL2_EM_94 { get; set; }
    public string? LEVEL1_EM_PTQ_EE { get; set; }
    public string? LEV2EM_94 { get; set; }
    public string? LEV2EM_95 { get; set; }
    public string? LEV1EM_PTQ_EE { get; set; }
    public string? LEV2SCIA_94 { get; set; }
    public string? LEV2SCIA_95 { get; set; }
    public string? LEV2SCIC_94 { get; set; }
    public string? LEV2SCIC_95 { get; set; }
    public string? LEV2SCID_94 { get; set; }
    public string? LEV2SCID_95 { get; set; }
    public string? LEV2SCI2_94 { get; set; }
    public string? LEV2SCI2_95 { get; set; }
    public string? LEVEL2MFL_94 { get; set; }
    public string? LEVEL2MFL_95 { get; set; }
    public string? LEVEL1MFL_PTQ_EE { get; set; }
    public string? ANYPMFL_PTQ_EE { get; set; }
    public string? GCSE_ENGATT_PTQ_EE { get; set; }
    public string? GCSE_ENG_91 { get; set; }
    public string? GCSE_ENG_94 { get; set; }
    public string? GCSE_ENG_95 { get; set; }
    public string? GCSE_MATHATT_PTQ_EE { get; set; }
    public string? GCSE_MATH_91 { get; set; }
    public string? GCSE_MATH_94 { get; set; }
    public string? GCSE_MATH_95 { get; set; }
    public string? GCSE_SCIATT_PTQ_EE { get; set; }
    public string? GCSE_SCI_91 { get; set; }
    public string? GCSE_SCI_94 { get; set; }
    public string? EBACENG_94 { get; set; }
    public string? EBACENG_95 { get; set; }
    public string? EBALLSCI_PTQ_EE { get; set; }
    public string? PASS2SCIA_94 { get; set; }
    public string? PASS2SCIA_95 { get; set; }
    public string? PASS2SCIB_94 { get; set; }
    public string? PASS2SCIB_95 { get; set; }
    public string? PASSCOMBSCI_94 { get; set; }
    public string? PASSCOMBSCI_95 { get; set; }
    public string? PASSCOMBSCI_91 { get; set; }
    public string? EBAC2SCI_94 { get; set; }
    public string? EBAC2SCI_95 { get; set; }
    public string? EBACMAT_94 { get; set; }
    public string? EBACMAT_95 { get; set; }
    public string? EBACHUM_94 { get; set; }
    public string? EBACHUM_95 { get; set; }
    public string? EBACLAN_94 { get; set; }
    public string? EBACLAN_95 { get; set; }
    public string? EBACC_94 { get; set; }
    public string? EBACC_95 { get; set; }
    public string? EBACCAPS_PUPIL { get; set; }
    public string? L2BASICS_94 { get; set; }
    public string? L2BASICS_95 { get; set; }
    public string? EBACENG_E_PTQ_EE { get; set; }
    public string? EBACMAT_E_PTQ_EE { get; set; }
    public string? EBAC2SCI_E_PTQ_EE { get; set; }
    public string? EBACHUM_E_PTQ_EE { get; set; }
    public string? EBACLAN_E_PTQ_EE { get; set; }
    public string? EBACC_E_PTQ_EE { get; set; }
    public string? EBACENG91 { get; set; }
    public string? PASS2SCIA_91 { get; set; }
    public string? PASS2SCIB_91 { get; set; }
    public string? EBAC2SCI_91 { get; set; }
    public string? EBACMAT91 { get; set; }
    public string? EBACHUM_91 { get; set; }
    public string? EBACLAN_91 { get; set; }
    public string? EBACC91 { get; set; }
    public string? INVAMOD_PTQ_EE { get; set; }
    public string? INSCIVAMOD_PTQ_EE { get; set; }
    public string? INHUMVAMOD_PTQ_EE { get; set; }
    public string? INLANVAMOD_PTQ_EE { get; set; }
    public string? INVACALC_PTQ_EE { get; set; }
    public string? INSCIVACALC_PTQ_EE { get; set; }
    public string? INHUMVACALC_PTQ_EE { get; set; }
    public string? INLANVACALC_PTQ_EE { get; set; }
    public string? VAP2TAENG_PTQ_EE { get; set; }
    public string? VAP2TAMAT_PTQ_EE { get; set; }
    public string? VAP2TAAPS_PTQ_EE { get; set; }
    public string? VAP2TAAPSSQ_PTQ_EE { get; set; }
    public string? VAP2TAAPSCU_PTQ_EE { get; set; }
    public string? P2TAE_DEV_PTQ_EE { get; set; }
    public string? P2TAM_DEV_PTQ_EE { get; set; }
    public string? VAPTSC_PTQ_EE { get; set; }
    public string? GPTSTNEWE_PTQ_EE { get; set; }
    public string? GPTSCNEWE_PTQ_EE { get; set; }
    public string? B8SCRPLUSBONUS_PTQ_EE { get; set; }
    public string? EBPTSENG_PTQ_EE { get; set; }
    public string? EBPTSMAT_PTQ_EE { get; set; }
    public string? EBPTSSCI_PTQ_EE { get; set; }
    public string? EBPTSHUM_PTQ_EE { get; set; }
    public string? EBPTSLAN_PTQ_EE { get; set; }
    public string? B8VAPRED_PTQ_EE { get; set; }
    public string? B8VASCR_PTQ_EE { get; set; }
    public string? ENGVAPRED_PTQ_EE { get; set; }
    public string? ENGVASCR_PTQ_EE { get; set; }
    public string? MATVAPRED_PTQ_EE { get; set; }
    public string? MATVASCR_PTQ_EE { get; set; }
    public string? SCIVAPRED_PTQ_EE { get; set; }
    public string? SCIVASCR_PTQ_EE { get; set; }
    public string? HUMVAPRED_PTQ_EE { get; set; }
    public string? HUMVASCR_PTQ_EE { get; set; }
    public string? LANVAPRED_PTQ_EE { get; set; }
    public string? LANVASCR_PTQ_EE { get; set; }
    public string? PRIORBAND_PTQ_EE { get; set; }
    public string? EALGRP_PTQ_EE { get; set; }
    public string? ENGPAIR_PTQ_EE { get; set; }
    public string? ENGPAIRLEV1_PTQ_EE { get; set; }
    public string? ENGPAIRLEV2_94 { get; set; }
    public string? ENGPAIRLEV2_95 { get; set; }
    public string? APELIT_91 { get; set; }
    public string? APFOOD_91 { get; set; }
    public string? APART_91 { get; set; }
    public string? APHIS_91 { get; set; }
    public string? APGEO_91 { get; set; }
    public string? APFRE_91 { get; set; }
    public string? APGER_91 { get; set; }
    public string? APBUS_91 { get; set; }
    public string? APRS_91 { get; set; }
    public string? APPE_91 { get; set; }
    public string? APPHY_91 { get; set; }
    public string? APCHE_91 { get; set; }
    public string? APBIO_91 { get; set; }
    public string? APDRA_91 { get; set; }
    public string? APSPAN_91 { get; set; }
    public string? APMUS_91 { get; set; }
    public string? APMAT_91 { get; set; }
    public string? APENG_91 { get; set; }
    public string? APSTAT_91 { get; set; }
    public string? APMFT_91 { get; set; }
    public string? APITA_91 { get; set; }
    public string? APMGRK_91 { get; set; }
    public string? APPOR_PTQ_EE { get; set; }
    public string? APARA_91 { get; set; }
    public string? APBEN_91 { get; set; }
    public string? APCHI_91 { get; set; }
    public string? APGUJ_PTQ_EE { get; set; }
    public string? APJAP_91 { get; set; }
    public string? APMHEB_91 { get; set; }
    public string? APPAN_91 { get; set; }
    public string? APPOL_91 { get; set; }
    public string? APRUS_91 { get; set; }
    public string? APTUR_PTQ_EE { get; set; }
    public string? APURD_91 { get; set; }
    public string? APPER_PTQ_EE { get; set; }
    public string? APCGRK_91 { get; set; }
    public string? APLAT_91 { get; set; }
    public string? APBHEB_PTQ_EE { get; set; }
    public string? APCOMBSCI_91 { get; set; }
    public string? ENGLISHBONUS_PTQ_EE { get; set; }
    public string? MATHSBONUS_PTQ_EE { get; set; }
    public string? HPGENG_PTQ_EE { get; set; }
    public string? HPGMATH_PTQ_EE { get; set; }
    public string? KS2ENG24P_PTQ_EE { get; set; }
    public string? KS2MAT24P_PTQ_EE { get; set; }
    public string? FSM { get; set; }
    public string? FSM6 { get; set; }
    public string? FSM6_P { get; set; }
    public string? SENPS { get; set; }
    public string? SENA { get; set; }
    public string? SENK { get; set; }
    public string? SENE { get; set; }
    public string? FEMALE { get; set; }
    public string? FLANG { get; set; }
    public string? TRIPLESCI_E { get; set; }
    public string? MULTILAN_E { get; set; }
    public string? NEWMOBILE { get; set; }
    public string? KS2EMFG { get; set; }
    public string? KS2EMFG_GRP { get; set; }
    public string? INP8MOD { get; set; }
    public string? INP8CALC { get; set; }
    public string? ENGRESID { get; set; }
    public string? ENGRESID_G { get; set; }
    public string? EBAC4 { get; set; }
    public string? EBAC5 { get; set; }
    public string? EBAC6 { get; set; }
    public string? EBAC4_G { get; set; }
    public string? EBAC5_G { get; set; }
    public string? EBAC6_G { get; set; }
    public string? OTH1 { get; set; }
    public string? OTH2 { get; set; }
    public string? OTH3 { get; set; }
    public string? OTH1_G { get; set; }
    public string? OTH2_G { get; set; }
    public string? OTH3_G { get; set; }
    public string? SLOT1ENG { get; set; }
    public string? SLOT2MAT { get; set; }
    public string? SLOT3EBAC { get; set; }
    public string? SLOT4EBAC { get; set; }
    public string? SLOT5EBAC { get; set; }
    public string? SLOT6OPEN { get; set; }
    public string? SLOT7OPEN { get; set; }
    public string? SLOT8OPEN { get; set; }
    public string? SLOT6OPEN_G { get; set; }
    public string? SLOT7OPEN_G { get; set; }
    public string? SLOT8OPEN_G { get; set; }
    public string? ATT8 { get; set; }
    public string? EBACFILL { get; set; }
    public string? OPENFILL { get; set; }
    public string? EBACSCR { get; set; }
    public string? OPENSCR { get; set; }
    public string? ATT8_PRED { get; set; }
    public string? P8SCORE { get; set; }
    public string? P8SCORE_ORIG { get; set; }
    public string? P8ADJ { get; set; }
    public string? AVGP8_GRP { get; set; }
    public string? SIGMAP8_GRP { get; set; }
    public string? P8THRESH { get; set; }
    public string? ENG_PRED { get; set; }
    public string? P8ENG { get; set; }
    public string? MAT_PRED { get; set; }
    public string? P8MAT { get; set; }
    public string? EBAC_PRED { get; set; }
    public string? P8EBAC { get; set; }
    public string? OPEN_PRED { get; set; }
    public string? P8OPEN { get; set; }
    public string? OPENGSCR { get; set; }
    public string? OPENNGSCR { get; set; }
    public string? KS4_2BTECEDEXDA_PTQ_EE { get; set; }
    public string? KS4_APARA_PTQ_EE { get; set; }
    public string? KS4_APART_PTQ_EE { get; set; }
    public string? KS4_APBEN_PTQ_EE { get; set; }
    public string? KS4_APBIO_PTQ_EE { get; set; }
    public string? KS4_APBIOE_PTQ_EE { get; set; }
    public string? KS4_APBUS_PTQ_EE { get; set; }
    public string? KS4_APCHE_PTQ_EE { get; set; }
    public string? KS4_APCHI_PTQ_EE { get; set; }
    public string? KS4_APDRA_PTQ_EE { get; set; }
    public string? KS4_APDTT_PTQ_EE { get; set; }
    public string? KS4_APDUT_PTQ_EE { get; set; }
    public string? KS4_APELEC_PTQ_EE { get; set; }
    public string? KS4_APELIT_PTQ_EE { get; set; }
    public string? KS4_APENG_PTQ_EE { get; set; }
    public string? KS4_APFOOD_PTQ_EE { get; set; }
    public string? KS4_APFRE_PTQ_EE { get; set; }
    public string? KS4_APGEO_PTQ_EE { get; set; }
    public string? KS4_APGER_PTQ_EE { get; set; }
    public string? KS4_APGRA_PTQ_EE { get; set; }
    public string? KS4_APHECD_PTQ_EE { get; set; }
    public string? KS4_APHIS_PTQ_EE { get; set; }
    public string? KS4_APIT_PTQ_EE { get; set; }
    public string? KS4_APITA_PTQ_EE { get; set; }
    public string? KS4_APJAP_PTQ_EE { get; set; }
    public string? KS4_APMAT_PTQ_EE { get; set; }
    public string? KS4_APMFT_PTQ_EE { get; set; }
    public string? KS4_APMGRK_PTQ_EE { get; set; }
    public string? KS4_APMHEB_PTQ_EE { get; set; }
    public string? KS4_APMUS_PTQ_EE { get; set; }
    public string? KS4_APOFT_PTQ_EE { get; set; }
    public string? KS4_APPAN_PTQ_EE { get; set; }
    public string? KS4_APPE_PTQ_EE { get; set; }
    public string? KS4_APPHY_PTQ_EE { get; set; }
    public string? KS4_APPOL_PTQ_EE { get; set; }
    public string? KS4_APRE_PTQ_EE { get; set; }
    public string? KS4_APRES_PTQ_EE { get; set; }
    public string? KS4_APRS_PTQ_EE { get; set; }
    public string? KS4_APSPAN_PTQ_EE { get; set; }
    public string? KS4_APSTAT_PTQ_EE { get; set; }
    public string? KS4_APSYS_PTQ_EE { get; set; }
    public string? KS4_EBAC2SCI_PTQ_EE { get; set; }
    public string? KS4_EBAC2SCIAG_PTQ_EE { get; set; }
    public string? KS4_EBACC_PTQ_EE { get; set; }
    public string? KS4_EBACCAG_PTQ_EE { get; set; }
    public string? KS4_EBACHUM_PTQ_EE { get; set; }
    public string? KS4_EBACHUMAG_PTQ_EE { get; set; }
    public string? KS4_EBACLAN_PTQ_EE { get; set; }
    public string? KS4_EBACLANAG_PTQ_EE { get; set; }
    public string? KS4_EBACMAT_PTQ_EE { get; set; }
    public string? KS4_EBACMATAG_PTQ_EE { get; set; }
    public string? KS4_EDEXDA_PTQ_EE { get; set; }
    public string? KS4_ENGPAIRLEV2_PTQ_EE { get; set; }
    public string? KS4_ENT1GMFL_PTQ_EE { get; set; }
    public string? KS4_FIVEAC_PTQ_EE { get; set; }
    public string? KS4_FIVEAG_PTQ_EE { get; set; }
    public string? KS4_GCSE_A_PTQ_EE { get; set; }
    public string? KS4_GCSE_AA_PTQ_EE { get; set; }
    public string? KS4_GCSE_AC_PTQ_EE { get; set; }
    public string? KS4_GCSE_AG_PTQ_EE { get; set; }
    public string? KS4_GCSE_ASTAR_PTQ_EE { get; set; }
    public string? KS4_GCSE_B_PTQ_EE { get; set; }
    public string? KS4_GCSE_C_PTQ_EE { get; set; }
    public string? KS4_GCSE_D_PTQ_EE { get; set; }
    public string? KS4_GCSE_DG_PTQ_EE { get; set; }
    public string? KS4_GCSE_E_PTQ_EE { get; set; }
    public string? KS4_GCSE_ENGAC_PTQ_EE { get; set; }
    public string? KS4_GCSE_ENGAG_PTQ_EE { get; set; }
    public string? KS4_GCSE_F_PTQ_EE { get; set; }
    public string? KS4_GCSE_G_PTQ_EE { get; set; }
    public string? KS4_GCSE_MATHAC_PTQ_EE { get; set; }
    public string? KS4_GCSE_MATHAG_PTQ_EE { get; set; }
    public string? KS4_GCSE_SCIAC_PTQ_EE { get; set; }
    public string? KS4_GCSE_SCIAG_PTQ_EE { get; set; }
    public string? KS4_GCSEVOC_PTQ_EE { get; set; }
    public string? KS4_GVOC_A_PTQ_EE { get; set; }
    public string? KS4_GVOC_AA_PTQ_EE { get; set; }
    public string? KS4_GVOC_AC_PTQ_EE { get; set; }
    public string? KS4_GVOC_AG_PTQ_EE { get; set; }
    public string? KS4_GVOC_ASTAR_PTQ_EE { get; set; }
    public string? KS4_GVOC_B_PTQ_EE { get; set; }
    public string? KS4_GVOC_C_PTQ_EE { get; set; }
    public string? KS4_GVOC_D_PTQ_EE { get; set; }
    public string? KS4_GVOC_DG_PTQ_EE { get; set; }
    public string? KS4_GVOC_E_PTQ_EE { get; set; }
    public string? KS4_GVOC_F_PTQ_EE { get; set; }
    public string? KS4_GVOC_G_PTQ_EE { get; set; }
    public string? KS4_HGMATH_PTQ_EE { get; set; }
    public string? KS4_KS4SCI_PTQ_EE { get; set; }
    public string? KS4_L2BASICS_1_PTQ_EE { get; set; }
    public string? KS4_L2BASICS_2_PTQ_EE { get; set; }
    public string? KS4_L2BASICS_3_PTQ_EE { get; set; }
    public string? KS4_L2BASICS_4_PTQ_EE { get; set; }
    public string? KS4_L2BASICS_LL_PTQ_EE { get; set; }
    public string? KS4_LEV2EM_PTQ_EE { get; set; }
    public string? KS4_LEV2SCI2_PTQ_EE { get; set; }
    public string? KS4_LEV2SCI2B_PTQ_EE { get; set; }
    public string? KS4_LEV2SCIA_PTQ_EE { get; set; }
    public string? KS4_LEV2SCIB_PTQ_EE { get; set; }
    public string? KS4_LEV2SCIC_PTQ_EE { get; set; }
    public string? KS4_LEV2SCID_PTQ_EE { get; set; }
    public string? KS4_LEV2SCIE_PTQ_EE { get; set; }
    public string? KS4_LEV2SCIF_PTQ_EE { get; set; }
    public string? KS4_LEV2SCIG_PTQ_EE { get; set; }
    public string? KS4_LEVEL2_EM_PTQ_EE { get; set; }
    public string? KS4_LEVEL2MFL_PTQ_EE { get; set; }
    public string? KS4_MATHPAIR_PTQ_EE { get; set; }
    public string? KS4_MFL_PTQ_EE { get; set; }
    public string? KS4_ONEAG_PTQ_EE { get; set; }
    public string? KS4_PASS_1AC_PTQ_EE { get; set; }
    public string? KS4_PASS_AASTAR_PTQ_EE { get; set; }
    public string? KS4_PASS_AASTAR5_PTQ_EE { get; set; }
    public string? KS4_PASS_ABSCI2_PTQ_EE { get; set; }
    public string? KS4_PASS_ABSCI2B_PTQ_EE { get; set; }
    public string? KS4_PASS_ABSCIA_PTQ_EE { get; set; }
    public string? KS4_PASS_ABSCIB_PTQ_EE { get; set; }
    public string? KS4_PASS_ABSCIC_PTQ_EE { get; set; }
    public string? KS4_PASS_ABSCID_PTQ_EE { get; set; }
    public string? KS4_PASS_ABSCIE_PTQ_EE { get; set; }
    public string? KS4_PASS_ABSCIF_PTQ_EE { get; set; }
    public string? KS4_PASS_AC_3NG_PTQ_EE { get; set; }
    public string? KS4_PASS_AG_PTQ_EE { get; set; }
    public string? KS4_PASS2SCIA_PTQ_EE { get; set; }
    public string? KS4_PASS2SCIAAG_PTQ_EE { get; set; }
    public string? KS4_PASS2SCIB_PTQ_EE { get; set; }
    public string? KS4_PASS2SCIBAG_PTQ_EE { get; set; }
    public string? KS4_PASSMATHPR_PTQ_EE { get; set; }
    public string? KS4_PASSMATHPRAG_PTQ_EE { get; set; }
    public string? KS4_PASSOTHSCI_PTQ_EE { get; set; }
    public string? KS4_PASSOTHSCIAG_PTQ_EE { get; set; }
    public string? KS4_VAP2TASCI_PTQ_EE { get; set; }
    public string? APBHEB_91 { get; set; }
    public string? APGUJ_91 { get; set; }
    public string? APPER_91 { get; set; }
    public string? APPOR_91 { get; set; }
    public string? APTUR_91 { get; set; }
    public string? EBACCSUBJENT_0 { get; set; }
    public string? EBACCSUBJENT_1 { get; set; }
    public string? EBACCSUBJENT_2 { get; set; }
    public string? EBACCSUBJENT_3 { get; set; }
    public string? EBACCSUBJENT_4 { get; set; }
    public string? ENTBASICS { get; set; }
    public string? ENTERED_ART { get; set; }
    public string? ENTERED_GEOGRAPHY { get; set; }
    public string? ENTERED_HIST_GEOG { get; set; }
    public string? ENTERED_HISTORY { get; set; }
    public string? FIVE91 { get; set; }
    public string? FIVE94 { get; set; }
    public string? GCSE_1 { get; set; }
    public string? GCSE_2 { get; set; }
    public string? GCSE_3 { get; set; }
    public string? GCSE_4 { get; set; }
    public string? GCSE_5 { get; set; }
    public string? GCSE_6 { get; set; }
    public string? GCSE_7 { get; set; }
    public string? GCSE_8 { get; set; }
    public string? GCSE_9 { get; set; }
    public string? GCSE_91 { get; set; }
    public string? GCSE_94 { get; set; }
    public string? GCSE_95 { get; set; }
    public string? KS2EMSS { get; set; }
    public string? KS2EMSS_GRP { get; set; }
    public string? KS2MATSCORE { get; set; }
    public string? KS2MATSCORETA { get; set; }
    public string? KS2READSCORE { get; set; }
    public string? KS2READSCORETA { get; set; }
    public string? PASS_1_91 { get; set; }
    public string? PASS_91 { get; set; }
    public string? APRUS_PTQ_EE { get; set; }
    public string? APURD_PTQ_EE { get; set; }
    public string? APCGRK_PTQ_EE { get; set; }
    public string? APLAT_PTQ_EE { get; set; }
    public string? APDSCI_PTQ_EE { get; set; }
    public string? APVBUS_PTQ_EE { get; set; }
    public string? APHSC_PTQ_EE { get; set; }
    public string? APLT_PTQ_EE { get; set; }
    public string? APVSCI_PTQ_EE { get; set; }
    public string? APSVSCI_PTQ_EE { get; set; }
    public string? APVIT_PTQ_EE { get; set; }
    public string? APCORESCI_PTQ_EE { get; set; }
    public string? APADTSCI_PTQ_EE { get; set; }
    public string? APAPDSCI_PTQ_EE { get; set; }
    public string? FLAG24ENGPRG_PTQ_EE { get; set; }
    public string? VERSION { get; set; }
}
