name: Deploy environment
run-name: Deploy ${{ github.ref_name }} to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true

permissions:
  contents: read

jobs:
  package:
    name: Package application
    uses: ./.github/workflows/package.yml
    permissions:
      contents: read  # Required to check out the code.
      packages: read  # Required to access the DfEDigital NuGet feed.

  deploy:
    name: Deploy to Azure App Service
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required to check out the code (for the smoke-test action).
      id-token: write # Required for OIDC authentication with Azure
    concurrency: deploy_${{ inputs.environment }}

    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy.outputs.app_url }}

    steps:
      - uses: actions/checkout@v6

      - name: Deploy to Azure
        id: deploy
        uses: ./.github/actions/deploy
        with:
          app_name: ${{ vars.AZURE_APP_NAME }}
          artifact_name: ${{ needs.package.outputs.artifact_name }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
