name: Package application

on:
  workflow_call:
    outputs:
      artifact_name:
        value: web_package

jobs:
  package:
    name: Build & package
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Required to check out the code.
      packages: read  # Required to access the DfEDigital NuGet feed.

    steps:
      - uses: actions/checkout@v6

      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # Pinned at v4.0.0

      - name: Setup .NET SDK from global.json
        uses: actions/setup-dotnet@v5

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Add DfEDigital NuGet Feed Credentials
        run: |
          dotnet nuget update source dfedigital \
            --configfile ./DfE.GIAP.All/nuget.config \
            --username USERNAME \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - name: Build front-end assets
        run: npm ci
        working-directory: ./DfE.GIAP.All/src/DfE.GIAP.Web

      - name: Run gulp
        run: |
          npm install -g gulp
          gulp default --gulpfile src/DfE.GIAP.Web/gulpfile.js --cwd src/DfE.GIAP.Web
        working-directory: ./DfE.GIAP.All

      - run: just package -c Release -o ${{ github.workspace }}/publish

      - uses: actions/upload-artifact@v6
        id: upload_app
        with:
          name: web_package
          path: publish
          if-no-files-found: error
